# Generated by Django 5.2.8 on 2025-11-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestrdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='ville',
            field=models.CharField(default='Alger', max_length=100),
        ),
    ]
