# Generated by Django 5.2.8 on 2025-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestrdv', '0002_medecin_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecin',
            name='ville',
            field=models.CharField(choices=[('Adrar', '01 - Adrar'), ('Chlef', '02 - Chlef'), ('Laghouat', '03 - Laghouat'), ('Oum El Bouaghi', '04 - Oum El Bouaghi'), ('Batna', '05 - Batna'), ('Béjaïa', '06 - Béjaïa'), ('Biskra', '07 - Biskra'), ('Béchar', '08 - Béchar'), ('Blida', '09 - Blida'), ('Bouira', '10 - Bouira'), ('Tamanrasset', '11 - Tamanrasset'), ('Tébessa', '12 - Tébessa'), ('Tlemcen', '13 - Tlemcen'), ('Tiaret', '14 - Tiaret'), ('Tizi Ouzou', '15 - Tizi Ouzou'), ('Alger', '16 - Alger'), ('Djelfa', '17 - Djelfa'), ('Jijel', '18 - Jijel'), ('Sétif', '19 - Sétif'), ('Saïda', '20 - Saïda'), ('Skikda', '21 - Skikda'), ('Sidi Bel Abbès', '22 - Sidi Bel Abbès'), ('Annaba', '23 - Annaba'), ('Guelma', '24 - Guelma'), ('Constantine', '25 - Constantine'), ('Médéa', '26 - Médéa'), ('Mostaganem', '27 - Mostaganem'), ("M'Sila", "28 - M'Sila"), ('Mascara', '29 - Mascara'), ('Ouargla', '30 - Ouargla'), ('Oran', '31 - Oran'), ('El Bayadh', '32 - El Bayadh'), ('Illizi', '33 - Illizi'), ('Bordj Bou Arreridj', '34 - Bordj Bou Arreridj'), ('Boumerdès', '35 - Boumerdès'), ('El Tarf', '36 - El Tarf'), ('Tindouf', '37 - Tindouf'), ('Tissemsilt', '38 - Tissemsilt'), ('El Oued', '39 - El Oued'), ('Khenchela', '40 - Khenchela'), ('Souk Ahras', '41 - Souk Ahras'), ('Tipaza', '42 - Tipaza'), ('Mila', '43 - Mila'), ('Aïn Defla', '44 - Aïn Defla'), ('Naâma', '45 - Naâma'), ('Aïn Témouchent', '46 - Aïn Témouchent'), ('Ghardaïa', '47 - Ghardaïa'), ('Relizane', '48 - Relizane'), ('Timimoun', '49 - Timimoun'), ('Bordj Badji Mokhtar', '50 - Bordj Badji Mokhtar'), ('Ouled Djellal', '51 - Ouled Djellal'), ('Béni Abbès', '52 - Béni Abbès'), ('In Salah', '53 - In Salah'), ('In Guezzam', '54 - In Guezzam'), ('Touggourt', '55 - Touggourt'), ('Djanet', '56 - Djanet'), ("El M'Ghair", "57 - El M'Ghair"), ('El Meniaa', '58 - El Meniaa')], default='Alger', max_length=50),
        ),
    ]
